version: '3'

services:
  mysql:
    container_name: mysql
    image: "mysql:8.0"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "database_name"
    volumes:
      - "./data:/var/lib/mysql"
    ports:
      - "3306:3306"
  phpmyadmin:
    container_name: phpmyadmin
    image: "phpmyadmin:latest"
    restart: always
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: "3306"
    ports:
      - "8080:80"
